{% set name = "drf-spectacular-sidecar" %}
{% set version = "2023.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/drf-spectacular-sidecar-{{ version }}.tar.gz
  sha256: 93ae17f348f992677fd343625dd1ebc0b59b7ec66684944b7797861bd9b33934

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - pip
  run:
    - python >=3.7,<3.11
    - django >=2.2

test:
  imports:
    - drf_spectacular_sidecar
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tfranzel/drf-spectacular-sidecar
  summary: Serve self-contained distribution builds of Swagger UI and Redoc with Django
  dev_url: https://github.com/tfranzel/drf-spectacular-sidecar
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
